simpleArgs: &simple-args
  privacyRatingSc: '0x6CC193c80a1d8E94A4580A186bef06D10f877040'
  numberOfAgreements: &number-of-agreements 2
  transactionDuration: &transactionDuration 50

test:
  name: registerSc
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with RegisterSc, adding subscriptions and confirm delivery transactions.
  workers:
    type: local
    number: 1
  rounds:
    - label: initialize
      description: >-
        Test description for the initializing the privacyRatingSc in registerSc
        contract.
      txNumber: 1
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/registerSc/initialize.js
        arguments: *simple-args
    - label: registerSeller
      description: >-
        Test description for registering sellers in the marketplace
      txNumber: *number-of-agreements 
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/registerSc/registerSeller.js
        arguments: *simple-args
    - label: registerBuyer
      description: >-
        Test description for registering buyers in the marketplace
        contract.
      txNumber: *number-of-agreements 
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/registerSc/registerBuyer.js
        arguments: *simple-args
    - label: registerAgreement
      description: >-
        Test description for registering agreement
        contract.
      txNumber: *number-of-agreements 
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/registerSc/registerAgreement.js
        arguments: *simple-args


    - label: addSubscriptions_10
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txDuration: *transactionDuration
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 1
    - label: confirmDelivery_wo_10
      description: >-
        Test description for confirming the delivery of data by buyer
      txDuration: *transactionDuration
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: benchmarks/scenario/registerSc/confirmDelivery_wo.js
        arguments:
          << : *simple-args
          index: 1

 
    - label: addSubscriptions_10
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txDuration: *transactionDuration
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 2
    - label: confirmDelivery_10
      description: >-
        Test description for confirming the delivery of data by buyer
      txDuration: *transactionDuration
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: benchmarks/scenario/registerSc/confirmDelivery.js
        arguments:
          << : *simple-args
          index: 2

 
 
