
simpleArgs: &simple-args
  privacyRatingSc: '0xa1fFc5f622503B2d83ae681711f5768445d9C9Fd'
  numberOfAgreements: &number-of-agreements 2
  transactionDuration: &transactionDuration 50

test:
  name: registerSc
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with RegisterSc, adding subscriptions and confirm delivery transactions.
  workers:
    type: local
    number: 1
  rounds:
    - label: initialize
      description: >-
        Test description for the initializing the privacyRatingSc in registerSc
        contract.
      txNumber: 1
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/registerSc_write/initialize.js
        arguments: *simple-args
    - label: registerBuyer_40
      description: >-
        Test description for registering buyers in the marketplace
        contract.
      txDuration: *transactionDuration
      rateControl:
        type: fixed-rate
        opts:
          tps: 40
      workload:
        module: benchmarks/scenario/registerSc_write/registerBuyer.js
        arguments: *simple-args

