simpleArgs: &simple-args
  privacyRatingSc: '0x7C993786009e84ABDBAdf9C6624c7b70896Be10d'
  numberOfAgreements: &number-of-agreements 2
  transactionDuration: &transactionDuration 50

test:
  name: registerSc
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with RegisterSc, adding subscriptions and confirm delivery transactions.
  workers:
    type: local
    number: 1
  rounds:
    - label: initialize
      description: >-
        Test description for the initializing the privacyRatingSc in registerSc
        contract.
      txNumber: 1
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/registerSc/initialize.js
        arguments: *simple-args
    - label: registerSeller
      description: >-
        Test description for registering sellers in the marketplace
      txNumber: *number-of-agreements 
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/registerSc/registerSeller.js
        arguments: *simple-args
    - label: registerBuyer
      description: >-
        Test description for registering buyers in the marketplace
        contract.
      txNumber: *number-of-agreements 
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/registerSc/registerBuyer.js
        arguments: *simple-args
    - label: registerAgreement
      description: >-
        Test description for registering agreement
        contract.
      txNumber: *number-of-agreements 
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/registerSc/registerAgreement.js
        arguments: *simple-args


    - label: addSubscriptions1
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1501
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 1
    - label: addSubscriptions2
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 1
    - label: addSubscriptions3
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 1
    - label: addSubscriptions4
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 1
    - label: addSubscriptions5
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 1
    - label: addSubscriptions6
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 1

 

    - label: confirmDelivery_wo_170
      description: >-
        Test description for confirming the delivery of data by buyer
      txDuration: *transactionDuration
      rateControl:
        type: fixed-rate
        opts:
          tps: 170
      workload:
        module: benchmarks/scenario/registerSc/confirmDelivery_wo.js
        arguments:
          << : *simple-args
          index: 1

 
    - label: addSubscriptions1
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1501
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 2
    - label: addSubscriptions2
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 2
    - label: addSubscriptions3
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 2
    - label: addSubscriptions4
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 2
    - label: addSubscriptions5
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1500
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 2
    - label: addSubscriptions6
      description: >-
        Test description for adding subscription details in the deployed
        contract.
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/registerSc/addSubscription.js
        arguments:
          << : *simple-args
          index: 2

 

    - label: confirmDelivery_170
      description: >-
        Test description for confirming the delivery of data by buyer
      txDuration: *transactionDuration
      rateControl:
        type: fixed-rate
        opts:
          tps: 170
      workload:
        module: benchmarks/scenario/registerSc/confirmDelivery.js
        arguments:
          << : *simple-args
          index: 2

 
 
